<a href="https://colab.research.google.com/github/aaubs/ds-master/blob/main/notebooks/M1_pandas_v5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Data Manipulation for Data Science

## 1. Introduction to the Main Elements of a Computer
#### **What are the core components of a computer and how do they interact in data processing?**

- Overview of hardware components: CPU, Memory, Storage, I/O devices.
- Introduction to software: Operating systems, application software.
- How hardware and software interact to perform data manipulation tasks.

In [ ]:
from IPython.display import YouTubeVideo

YouTubeVideo('ExxFxD4OSZ0', start=120)

### Exercise 1
Check Out the Computer Resources (CPU, RAM, Storage, and GPU) on Your Computer and Google Colab



## 2. Overview of Programming Languages
#### **What are the different types of programming languages, and how are they used in various domains?**

- Classification of programming languages: High-level vs. low-level, interpreted vs. compiled.
- Popular programming languages and their uses: Java, C++, JavaScript, Python, R.
- Introduction to domain-specific languages: SQL for databases, HTML/CSS for web development.

#### **Why do data scientists prefer Python over other programming languages?**

- Ease of learning and readability: Emphasis on readability, simplicity, and use of whitespace.
- Rich ecosystem of libraries tailored for data science: numpy, pandas, matplotlib, scikit-learn.
- Community and support: Large community, extensive documentation, and abundance of learning resources.
- Flexibility and integration: Ability to integrate with other languages and tools.

## Why Learn NumPy and pandas First?
NumPy and pandas are two of the most widely used Python libraries, especially in the fields of data science, machine learning, and scientific computing. NumPy and pandas are fundamental libraries for handling and analyzing data in Python, making them crucial for anyone starting a career in data science.

Screenshot 2024-08-30 at 10.41.45.png

#3. Introduction to NumPy

In [ ]:
# Import numpy as np and check the version
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
# Create a 1D array of numbers from 0 to 9



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5])

In [ ]:
# Create a 3x3 array of normally distributed random values with mean 2 and standard deviation 3


In [ ]:
x

array([[ 4.36252262,  1.58456702,  4.79127714],
       [ 7.37050729, 12.53433367,  0.91103284],
       [ 2.39391193,  2.60473797,  2.24385553]])

#### Exercise 2:
Create a 2D array of numbers from 0 to 9


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##  3.1. Attribute of array


In [ ]:
# Create a 3x3 array of normally distributed random values with mean 2 and standard deviation 3
# and check its size, dimension, shape, the data type, itemsize and the total size of the array
x = np.random.normal(2, 3, (3, 3))

print("x array: ", x)
print("x3 ndim: ", x.)
print("x3 shape:", x.)
print("x3 size: ", x.)
print("x3 data type: ", x.)
print("x3 itemsize: ", x.)
print("x3 totla size: ", x.)

x array:  [[ 6.53360422  3.54909271  0.61421793]
 [ 0.91304559  0.78060081 -3.3400837 ]
 [-0.34557636  0.9162133   0.35958003]]
x3 ndim:  2
x3 shape: (3, 3)
x3 size:  9
x3 data type:  float64
x3 itemsize:  8
x3 totla size:  72


## 3.2. Fancy Indexing


In [ ]:
# A. Create a 1D array of numbers from 0 to 20


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# B. update the values of 1, 4, 5, 7, 11, 14, 19 with -2 and next multiply it by 5


array([ 0, -2,  2,  3, -2, -2,  6, -2,  8,  9, 10, -2, 12, 13, -2, 15, 16,
       17, 18, -2])

In [ ]:
# C. multiply it by 5



array([  0, -10,   2,   3, -10, -10,   6, -10,   8,   9,  10, -10,  12,
        13, -10,  15,  16,  17,  18, -10])

#### Exercise 3:
- A. Create a 1D array of numbers from 0 to 25
- B. Replace the values at positions 2, 5, 8, 12, 16, 20, and 24 with -1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

array([ 0,  1, -1,  3,  4, -1,  6,  7, -1,  9, 10, 11, -1, 13, 14, 15, -1,
       17, 18, 19, -1, 21, 22, 23, -1])

In [ ]:
import numpy as np

state = ['California', 'Texas', 'New York', 'Florida', 'Illinois']
population = [38332521, 26448193, 19651127, 19552860, 12882135]
area = [423967, 695662, 141297, 170312, 149995]

# Specify the data types (Unicode strings or int) and names for each column
dtype = [('state', 'U10'), ('population', int), ('area', int)]

# Create a structured array using the dtype
data = np.array(list(zip(state, population, area)), dtype=dtype)

print(data)

[('California', 38332521, 423967) ('Texas', 26448193, 695662)
 ('New York', 19651127, 141297) ('Florida', 19552860, 170312)
 ('Illinois', 12882135, 149995)]


# 4. Introduction to Pandas (chapter 3)


In [ ]:
# Import Pandas as pd and check the version
import pandas as pd
pd.__version__

'2.1.4'

In [ ]:
# Create a DataFrame object From the structured array


state  population    area
0  California    38332521  423967
1       Texas    26448193  695662
2    New York    19651127  141297
3     Florida    19552860  170312
4    Illinois    12882135  149995

In general we can categorize all important subjects of Pandas into 7 groups:


1.   **Indexing**
2.   **Accessing and Filtering data**
3.   Universal functions
4.   **Missing values**
5.   Multindexing
6.   **Combining datasets**
7.   **Aggregation**



In this tutorial, we focus on Accessing data, Missing values, Combining datasets, and aggregation.

# Project Title - Udemy Courses Exploratory Data Analysis
## About the Dataset
These dataset contains 3678 course related information which are categorised in four subjects.

Source of the dataset : https://www.kaggle.com/andrewmvd/udemy-courses



## Setup

First, import pandas and load the dataset:


In [ ]:
import pandas as pd

# Load the dataset
url = 'https://raw.githubusercontent.com/aaubs/ds-master/main/data/udemy_courses_info.csv'
df = pd.read_csv(url)

# 1. Indexing

a. Implicit Indexing

Implicit indexing in pandas refers to accessing elements directly without specifying an index.

RangeIndex(start=0, stop=2959, step=1)

In [ ]:
# Example: Retrieving the first 5 courses info.


course_id                                       course_title  \
0    1006314  Financial Modeling for Business Analysts and C...   
1    1011058       How To Maximize Your Profits Trading Options   
2     192870  Trading Penny Stocks: A Guide for All Levels I...   
3     739964  Investing And Trading For Beginners: Mastering...   
4     403100  Trading Stock Chart Patterns For Immediate Exp...   

                                                 url  is_paid  price  \
0  https://www.udemy.com/financial-modeling-for-b...     True     45   
1  https://www.udemy.com/how-to-maximize-your-pro...     True    200   
2  https://www.udemy.com/trading-penny-stocks-a-g...     True    150   
3  https://www.udemy.com/investing-and-trading-fo...     True     65   
4  https://www.udemy.com/trading-chart-patterns-f...     True     95   

   num_subscribers  num_reviews  num_lectures               level  \
0             2174         74.0          51.0  Intermediate Level   
1             1276         45.0          26.0  Intermediate Level   
2             9221        138.0          25.0          All Levels   
3             1540        178.0          26.0      Beginner Level   
4             2917        148.0          23.0          All Levels   

   content_duration           subject  
0               2.5  Business Finance  
1               2.0  Business Finance  
2               3.0  Business Finance  
3               1.0  Business Finance  
4               2.5  Business Finance

#### Exercise 4:

Using implicit indexing, retrieve info of raw 3 to 6.

In [ ]:
# Your turn: Write the code to retrieve info of raw 3 to 6.
# Solution:


course_id                                       course_title  \
3     739964  Investing And Trading For Beginners: Mastering...   
4     403100  Trading Stock Chart Patterns For Immediate Exp...   
5     476268  Options Trading 3 : Advanced Stock Profit and ...   

                                                 url  is_paid  price  \
3  https://www.udemy.com/investing-and-trading-fo...     True     65   
4  https://www.udemy.com/trading-chart-patterns-f...     True     95   
5  https://www.udemy.com/day-trading-stock-option...     True    195   

   num_subscribers  num_reviews  num_lectures           level  \
3             1540        178.0          26.0  Beginner Level   
4             2917        148.0          23.0      All Levels   
5             5172         34.0          38.0    Expert Level   

   content_duration           subject  
3               1.0  Business Finance  
4               2.5  Business Finance  
5               2.5  Business Finance

####b. Explicit Indexing
Pandas allows you to access data using explicit indexes, either by label or integer location.

RangeIndex(start=0, stop=2959, step=1)

Index(['course_id', 'course_title', 'url', 'is_paid', 'price',
       'num_subscribers', 'num_reviews', 'num_lectures', 'level',
       'content_duration', 'subject'],
      dtype='object')

Index([1006314, 1011058,  192870,  739964,  403100,  476268,  592338,  975046,
        742602,  794151,
       ...
        523216,  270976,  679992,  330900,  667122,  865438,  775618,  635248,
        905096,  297602],
      dtype='int64', name='course_id', length=2959)

In [ ]:
df.head(2)

index                                       course_title  \
course_id                                                             
1006314        0  Financial Modeling for Business Analysts and C...   
1011058        1       How To Maximize Your Profits Trading Options   

                                                         url  is_paid  price  \
course_id                                                                      
1006314    https://www.udemy.com/financial-modeling-for-b...     True     45   
1011058    https://www.udemy.com/how-to-maximize-your-pro...     True    200   

           num_subscribers  num_reviews  num_lectures               level  \
course_id                                                                   
1006314               2174         74.0          51.0  Intermediate Level   
1011058               1276         45.0          26.0  Intermediate Level   

           content_duration           subject  
course_id                                      
1006314                 2.5  Business Finance  
1011058                 2.0  Business Finance

# 2. Accessing and Filtering Data


## a. Simple Indexing
Simple indexing involves selecting specific rows or columns using square brackets.

In [ ]:
# Example: Selecting 'course_title' column for the first 10 courses.


0    Financial Modeling for Business Analysts and C...
1         How To Maximize Your Profits Trading Options
2    Trading Penny Stocks: A Guide for All Levels I...
3    Investing And Trading For Beginners: Mastering...
4    Trading Stock Chart Patterns For Immediate Exp...
5    Options Trading 3 : Advanced Stock Profit and ...
6    Forex Trading Secrets of the Pros With Amazon'...
7                      Trading Options With Money Flow
8    Financial Management Risk and Return For Secur...
9    Forex Trading Course: Work Smarter Not Harder ...
Name: course_title, dtype: object

#### Exercise 5:

Select and display the 'price' column for the first 10 courses.



In [ ]:
# Your turn: Write the code to select and display 'price' columns for the first 10 courses.
# Solution:


0     45
1    200
2    150
3     65
4     95
5    195
6    200
7    200
8     30
9    195
Name: price, dtype: int64

b. Slicing Indexing

Slicing allows you to select a range of data.

In [ ]:
# Example: Slicing and displaying courses and num_subscribers from index 50 to 60.



                                         course_title  num_subscribers
50  Forex Strategies: Kelly Criterion Larry Willia...             5528
51  Elite Trend Trader: Learn To Trade Stocks Opti...             6451
52  Options Trading Introduction: Day Trade Stock ...            12394
53  Forex Trading -  Learn to Trade Forex Like the...             3223
54  Learn to Trade for Profit:Trading with Japanes...            16385
55  What Finance Job is for You? Explanation of 14...             2951
56         The Blueprint for Successful Stock Trading             2697
57         Trading for Beginners - Intermediate Level             3979
58     Start Trading Stocks Using Technical Analysis!             3190
59  VPS for Forex Trading - Protect Your Forex Robots             4252
60  Introduction to Accounting: The Language of Bu...            11958


In [ ]:
# Example: Selecting 'course_title' and 'num_reviews' for courses at index positions 0, 100, and 200.


     course_id  price
0      1006314     45
100    1051570     50
200     302450     20


#### Exercise 6:

Slice and display courses from index 50 to 60 and show only 'course_title' and 'price'.

In [ ]:
# Your turn: Write the code to slice and display courses and price from index 50 to 60 using loc and iloc.
# Solution:



                                         course_title  price
50  Forex Strategies: Kelly Criterion Larry Willia...    185
51  Elite Trend Trader: Learn To Trade Stocks Opti...    125
52  Options Trading Introduction: Day Trade Stock ...     95
53  Forex Trading -  Learn to Trade Forex Like the...     20
54  Learn to Trade for Profit:Trading with Japanes...     60
55  What Finance Job is for You? Explanation of 14...    200
56         The Blueprint for Successful Stock Trading    120
57         Trading for Beginners - Intermediate Level    150
58     Start Trading Stocks Using Technical Analysis!     25
59  VPS for Forex Trading - Protect Your Forex Robots    160
60  Introduction to Accounting: The Language of Bu...     20


c. Boolean Indexing

Boolean indexing is used to filter data based on conditions.

In [ ]:
# Example: Filtering courses with a price above 150


index  course_id                                       course_title  \
1      1    1011058       How To Maximize Your Profits Trading Options   
5      5     476268  Options Trading 3 : Advanced Stock Profit and ...   
6      6     592338  Forex Trading Secrets of the Pros With Amazon'...   
7      7     975046                    Trading Options With Money Flow   
9      9     794151  Forex Trading Course: Work Smarter Not Harder ...   

                                                 url  is_paid  price  \
1  https://www.udemy.com/how-to-maximize-your-pro...     True    200   
5  https://www.udemy.com/day-trading-stock-option...     True    195   
6  https://www.udemy.com/trading-with-amazons-aws...     True    200   
7  https://www.udemy.com/trading-options-using-mo...     True    200   
9  https://www.udemy.com/the-complete-trading-cou...     True    195   

   num_subscribers  num_reviews  num_lectures               level  \
1             1276         45.0          26.0  Intermediate Level   
5             5172         34.0          38.0        Expert Level   
6             4284         93.0          76.0          All Levels   
7             1380         42.0          17.0          All Levels   
9             4061         52.0          16.0          All Levels   

   content_duration           subject  
1               2.0  Business Finance  
5               2.5  Business Finance  
6               5.0  Business Finance  
7               1.0  Business Finance  
9               2.0  Business Finance

d. Fancy Indexing

Fancy indexing is the ability to select subsets of data using lists of index positions or labels.



In [ ]:
# Example: Selecting 'course_title' and 'num_reviews'


course_title  num_reviews
0     Financial Modeling for Business Analysts and C...         74.0
1          How To Maximize Your Profits Trading Options         45.0
2     Trading Penny Stocks: A Guide for All Levels I...        138.0
3     Investing And Trading For Beginners: Mastering...        178.0
4     Trading Stock Chart Patterns For Immediate Exp...        148.0
...                                                 ...          ...
2954    jQuery UI in Action: Build 5 jQuery UI Projects         28.0
2955  Learn jQuery from Scratch - Master of JavaScri...         14.0
2956                      Learn and Build using Polymer        169.0
2957  CSS Animations: Create Amazing Effects on Your...         31.0
2958  Using MODX CMS to Build Websites: A Beginner's...         36.0

[2959 rows x 2 columns]

#### Exercise 7:

Select and display the 'course_title',  'num_reviews', and 'price

course_title  num_reviews  price
0     Financial Modeling for Business Analysts and C...         74.0     45
1          How To Maximize Your Profits Trading Options         45.0    200
2     Trading Penny Stocks: A Guide for All Levels I...        138.0    150
3     Investing And Trading For Beginners: Mastering...        178.0     65
4     Trading Stock Chart Patterns For Immediate Exp...        148.0     95
...                                                 ...          ...    ...
2954    jQuery UI in Action: Build 5 jQuery UI Projects         28.0    150
2955  Learn jQuery from Scratch - Master of JavaScri...         14.0    100
2956                      Learn and Build using Polymer        169.0     40
2957  CSS Animations: Create Amazing Effects on Your...         31.0     50
2958  Using MODX CMS to Build Websites: A Beginner's...         36.0     45

[2959 rows x 3 columns]

# 3. Handling Missing Values


a. Detecting Missing Values


Pandas provides methods to detect missing values.

In [ ]:
# Example: Checking for missing values in the dataset.


index                 0
course_id             0
course_title          0
url                   0
is_paid               0
price                 0
num_subscribers       0
num_reviews         157
num_lectures         79
level                 0
content_duration     79
subject               0
dtype: int64

b. Dropping Missing Values

You can drop rows or columns with missing values using dropna()

- axis : {0 or 'index', 1 or 'columns'}


- how : {'any', 'all'}

c. Filling Missing Values

Filling missing data can be done using fillna()

In [ ]:
# Example: Filling missing values in the 'num_reviews' column with the average num_reviews.


0

#### Exercise 8:

Fill missing values in the 'num_reviews' column using ffill (Forward Fill) or bfill (Backward Fill)





<ipython-input-81-06802e210af1>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['num_reviews'].fillna(method='ffill', inplace=True)


# 4. Combining DataFrames

a. Not Requiring Overlapping

You can concatenate or append dataframes without requiring overlapping indices.

In [ ]:
# Read data for 2017
df_courses_2017 = pd.read_csv('https://raw.githubusercontent.com/aaubs/ds-master/main/data/udemy_courses_2017.csv')
df_courses_2017.head(2)

course_id                                       course_title  \
0    1070968                 Ultimate Investment Banking Course   
1    1113822  Complete GST Course & Certification - Grow You...   

                                                 url  is_paid  price  \
0  https://www.udemy.com/ultimate-investment-bank...     True    200   
1      https://www.udemy.com/goods-and-services-tax/     True     75   

   num_subscribers  num_reviews  num_lectures       level  content_duration  \
0             2147         23.0          51.0  All Levels               1.5   
1             2792        923.0         274.0  All Levels               NaN   

            subject  year  revenue  
0  Business Finance  2017   429400  
1  Business Finance  2017   209400

In [ ]:
df_courses_2017.shape

(713, 13)

Index(['index', 'course_id', 'course_title', 'url', 'is_paid', 'price',
       'num_subscribers', 'num_reviews', 'num_lectures', 'level',
       'content_duration', 'subject'],
      dtype='object')

b. Requiring Overlapping

Merging dataframes requires some overlap in the indices or keys.


In [ ]:
import pandas as pd

# Assuming you already have the Udemy dataset loaded as df
url = 'https://raw.githubusercontent.com/aaubs/ds-master/main/data/udemy_courses_info.csv'
udemy_df = pd.read_csv(url)

# Simulating an instructor dataset
instructors = pd.DataFrame({
    'instructor_id': [101, 102, 103, 104],
    'instructor_name': ['John Doe', 'Jane Smith', 'Emily Wright', 'Mike Brown'],
    'biography': [
        'Data Scientist with 10 years of experience.',
        'Expert in Machine Learning and AI technologies.',
        'Award-winning AI researcher.',
        'Senior Data Analyst with expertise in data visualization.'
    ],
    'course_id': udemy_df['course_id'].sample(4, random_state=1).values  # Randomly assigning course IDs for the example
})

# Display the instructor dataframe
instructors

instructor_id instructor_name  \
0            101        John Doe   
1            102      Jane Smith   
2            103    Emily Wright   
3            104      Mike Brown   

                                           biography  course_id  
0        Data Scientist with 10 years of experience.     537748  
1    Expert in Machine Learning and AI technologies.     502588  
2                       Award-winning AI researcher.     865634  
3  Senior Data Analyst with expertise in data vis...     521072

(3672, 14)

(4, 4)

(3672, 17)

In [ ]:
merged_df.head(2)

index  course_id                                       course_title  \
0    0.0    1006314  Financial Modeling for Business Analysts and C...   
1    1.0    1011058       How To Maximize Your Profits Trading Options   

                                                 url  is_paid  price  \
0  https://www.udemy.com/financial-modeling-for-b...     True     45   
1  https://www.udemy.com/how-to-maximize-your-pro...     True    200   

   num_subscribers  num_reviews  num_lectures               level  \
0             2174         74.0          51.0  Intermediate Level   
1             1276         45.0          26.0  Intermediate Level   

   content_duration           subject  year  revenue  instructor_id  \
0               2.5  Business Finance   NaN      NaN            NaN   
1               2.0  Business Finance   NaN      NaN            NaN   

  instructor_name biography  
0             NaN       NaN  
1             NaN       NaN

# 5. Aggregation

a. Simple Aggregation

You can perform data aggregation in pandas easily using functions such as sum, mean, and others.

In [ ]:
# Example: Finding the average number of subscribers.



3625.175397093613

b. Advanced Aggregation

Advanced aggregations might involve grouping data and applying functions.

In [ ]:
# Example: Grouping by 'subject' and calculating total subscribers and average rating.



num_subscribers      price
subject                                        
Business Finance             1738412  64.865702
Graphic Design                907807  55.324385
Musical Instruments           779127  49.207746
Web Development              7301548  75.035861